logging.level.org.springframework.security: DEBUG

server.port: 8089

security:
 oauth2:
   client:
     clientId: client-app-1
     clientSecret: 123
   resource:
#     tokenInfoUri: http://localhost:8090/oauth2/check_token
#     userInfoUri: http://localhost:8090/oauth2/userinfo
     jwk:
       key-set-uri: http://localhost:8090/key-set/.well-known/auth-server-sign-jwt.json
        
