CREATE TABLE USR_USER (
	USR_ID INT AUTO_INCREMENT PRIMARY KEY,
	USR_PASSWORD VARCHAR(255),
	USR_USERNAME VARCHAR(255)
);

CREATE TABLE USL_USER_LEVEL (
	USL_ID INT AUTO_INCREMENT PRIMARY KEY,
	USL_LEVEL VARCHAR(255),
	USR_ID INT NOT NULL,
	FOREIGN KEY (USR_ID) REFERENCES USR_USER(USR_ID)
);
