INSERT INTO USR_USER (USR_USERNAME,USR_PASSWORD) VALUES ('admin','$2a$10$hMFWGmS29BjVHEy0LOHs2O.HBX0.FiF3yH0gB9bHLsydPjx4ZFI.m');
INSERT INTO USR_USER (USR_USERNAME,USR_PASSWORD) VALUES ('customer','$2a$10$hMFWGmS29BjVHEy0LOHs2O.HBX0.FiF3yH0gB9bHLsydPjx4ZFI.m');
INSERT INTO USR_USER (USR_USERNAME,USR_PASSWORD) VALUES ('visitor','$2a$10$hMFWGmS29BjVHEy0LOHs2O.HBX0.FiF3yH0gB9bHLsydPjx4ZFI.m');
INSERT INTO USL_USER_LEVEL (USL_LEVEL,USR_ID) VALUES ('ROLE_ADMIN', 1);
INSERT INTO USL_USER_LEVEL (USL_LEVEL,USR_ID) VALUES ('ROLE_CUSTOMER', 2);
