INSERT INTO PUBLIC."USR_USER" (USR_ID,USR_USERNAME,USR_PASSWORD) VALUES (1,'admin','$2a$10$hMFWGmS29BjVHEy0LOHs2O.HBX0.FiF3yH0gB9bHLsydPjx4ZFI.m');
INSERT INTO PUBLIC."USR_USER" (USR_ID,USR_USERNAME,USR_PASSWORD) VALUES (2,'customer','$2a$10$hMFWGmS29BjVHEy0LOHs2O.HBX0.FiF3yH0gB9bHLsydPjx4ZFI.m');
INSERT INTO PUBLIC."USR_USER" (USR_ID,USR_USERNAME,USR_PASSWORD) VALUES (3,'visitor','$2a$10$hMFWGmS29BjVHEy0LOHs2O.HBX0.FiF3yH0gB9bHLsydPjx4ZFI.m');
INSERT INTO PUBLIC."USL_USER_LEVEL" (USL_ID,USL_LEVEL,USR_ID) VALUES (1,'ROLE_ADMIN', 1);
INSERT INTO PUBLIC."USL_USER_LEVEL" (USL_ID,USL_LEVEL,USR_ID) VALUES (2,'ROLE_CUSTOMER', 2);
