#logging.level.org.springframework: DEBUG

server.port: 8090

security:
  oauth2:
    client:
      client-id: client-app-1
      client-secret: 123
  authorization:
    check-token-access: permitAll()
    token-key-access: permitAll()
