#logging.level.org.springframework: DEBUG

server.port: 8080

jwt.secret: anySecretKey

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multi-auth-client
    #url: jdbc:h2:tcp://127.0.1.1:9092/~/Dev/Programs/H2Database/h2/databases/multi-auth-client
    #url: jdbc:h2:tcp://localhost/~/Dev/Programs/H2Database/h2/databases/multi-auth-client
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        hbm2ddl:
          auto: none

  main:
    allow-circular-references: true